# Generated by Django 4.1 on 2022-08-09 22:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Entries",
            new_name="Application",
        ),
    ]
